/* This file had been generated by python/tetraquarks.py
 * 
 * The executed command has been:
 * python tetraquarks_v3.py PLEGMA_heavy_light_tetraquarks_arrays.cuh PLEGMA_heavy_light_tetraquarks_arrays.cu
 * 
 * The gamma used are :
 * gx = [   0,  0,  0,  I,
 *          0,  0,  I,  0,
 *          0, -I,  0,  0,
 *         -I,  0,  0,  0, ] 
 * gy = [   0,  0,  0,  1,
 *          0,  0, -1,  0,
 *          0, -1,  0,  0,
 *          1,  0,  0,  0, ] 
 * gz = [   0,  0,  I,  0,
 *          0,  0,  0, -I,
 *         -I,  0,  0,  0,
 *          0,  I,  0,  0, ] 
 * gt = [   1,  0,  0,  0,
 *          0,  1,  0,  0,
 *          0,  0, -1,  0,
 *          0,  0,  0, -1, ] 
 *
 * bbud : {'flavs': ['bt^-up-bt^-dn'], 'coeffs': [1], 'spin': 1}
 * bbus : {'flavs': ['bt^-up-bt^-sr'], 'coeffs': [1], 'spin': 1}
 */
#pragma once
extern float2 bbud_g5_gj_g5_gj_ll_vals[768];
extern short bbud_g5_gj_g5_gj_ll_idxs[768*8];
extern short bbud_g5_gj_g5_gj_ll_col_contr[768*8];
extern float2 bbud_g5_gj_gj_g5_ll_vals[768];
extern short bbud_g5_gj_gj_g5_ll_idxs[768*8];
extern short bbud_g5_gj_gj_g5_ll_col_contr[768*8];
extern float2 bbud_gj_g5_g5_gj_ll_vals[768];
extern short bbud_gj_g5_g5_gj_ll_idxs[768*8];
extern short bbud_gj_g5_g5_gj_ll_col_contr[768*8];
extern float2 bbud_gj_g5_gj_g5_ll_vals[768];
extern short bbud_gj_g5_gj_g5_ll_idxs[768*8];
extern short bbud_gj_g5_gj_g5_ll_col_contr[768*8];
extern float2 bbud_gi_gj_g5_gk_ll_vals[768];
extern short bbud_gi_gj_g5_gk_ll_idxs[768*8];
extern short bbud_gi_gj_g5_gk_ll_col_contr[768*8];
extern float2 bbud_gi_gj_gk_g5_ll_vals[768];
extern short bbud_gi_gj_gk_g5_ll_idxs[768*8];
extern short bbud_gi_gj_gk_g5_ll_col_contr[768*8];
extern float2 bbud_g5_gk_gi_gj_ll_vals[768];
extern short bbud_g5_gk_gi_gj_ll_idxs[768*8];
extern short bbud_g5_gk_gi_gj_ll_col_contr[768*8];
extern float2 bbud_gk_g5_gi_gj_ll_vals[768];
extern short bbud_gk_g5_gi_gj_ll_idxs[768*8];
extern short bbud_gk_g5_gi_gj_ll_col_contr[768*8];
extern float2 bbud_gi_gj_gk_gl_ll_vals[1152];
extern short bbud_gi_gj_gk_gl_ll_idxs[1152*8];
extern short bbud_gi_gj_gk_gl_ll_col_contr[1152*8];
extern float2 bbud_g5_gj_gjC_Cg5_ll_vals[768];
extern short bbud_g5_gj_gjC_Cg5_ll_idxs[768*8];
extern short bbud_g5_gj_gjC_Cg5_ll_col_contr[768*8];
extern float2 bbud_gj_g5_gjC_Cg5_ll_vals[768];
extern short bbud_gj_g5_gjC_Cg5_ll_idxs[768*8];
extern short bbud_gj_g5_gjC_Cg5_ll_col_contr[768*8];
extern float2 bbud_gi_gj_gkC_Cg5_ll_vals[768];
extern short bbud_gi_gj_gkC_Cg5_ll_idxs[768*8];
extern short bbud_gi_gj_gkC_Cg5_ll_col_contr[768*8];
extern float2 bbud_gjC_Cg5_g5_gj_ll_vals[768];
extern short bbud_gjC_Cg5_g5_gj_ll_idxs[768*8];
extern short bbud_gjC_Cg5_g5_gj_ll_col_contr[768*8];
extern float2 bbud_gjC_Cg5_gj_g5_ll_vals[768];
extern short bbud_gjC_Cg5_gj_g5_ll_idxs[768*8];
extern short bbud_gjC_Cg5_gj_g5_ll_col_contr[768*8];
extern float2 bbud_gkC_Cg5_gi_gj_ll_vals[768];
extern short bbud_gkC_Cg5_gi_gj_ll_idxs[768*8];
extern short bbud_gkC_Cg5_gi_gj_ll_col_contr[768*8];
extern float2 bbud_gjC_Cg5_gjC_Cg5_ll_vals[768];
extern short bbud_gjC_Cg5_gjC_Cg5_ll_idxs[768*8];
extern short bbud_gjC_Cg5_gjC_Cg5_ll_col_contr[768*8];
extern float2 bbus_g5_gj_g5_gj_ll_vals[768];
extern short bbus_g5_gj_g5_gj_ll_idxs[768*8];
extern short bbus_g5_gj_g5_gj_ll_col_contr[768*8];
extern float2 bbus_g5_gj_gj_g5_ll_vals[768];
extern short bbus_g5_gj_gj_g5_ll_idxs[768*8];
extern short bbus_g5_gj_gj_g5_ll_col_contr[768*8];
extern float2 bbus_gj_g5_g5_gj_ll_vals[768];
extern short bbus_gj_g5_g5_gj_ll_idxs[768*8];
extern short bbus_gj_g5_g5_gj_ll_col_contr[768*8];
extern float2 bbus_gj_g5_gj_g5_ll_vals[768];
extern short bbus_gj_g5_gj_g5_ll_idxs[768*8];
extern short bbus_gj_g5_gj_g5_ll_col_contr[768*8];
extern float2 bbus_gi_gj_g5_gk_ll_vals[768];
extern short bbus_gi_gj_g5_gk_ll_idxs[768*8];
extern short bbus_gi_gj_g5_gk_ll_col_contr[768*8];
extern float2 bbus_gi_gj_gk_g5_ll_vals[768];
extern short bbus_gi_gj_gk_g5_ll_idxs[768*8];
extern short bbus_gi_gj_gk_g5_ll_col_contr[768*8];
extern float2 bbus_g5_gk_gi_gj_ll_vals[768];
extern short bbus_g5_gk_gi_gj_ll_idxs[768*8];
extern short bbus_g5_gk_gi_gj_ll_col_contr[768*8];
extern float2 bbus_gk_g5_gi_gj_ll_vals[768];
extern short bbus_gk_g5_gi_gj_ll_idxs[768*8];
extern short bbus_gk_g5_gi_gj_ll_col_contr[768*8];
extern float2 bbus_gi_gj_gk_gl_ll_vals[1152];
extern short bbus_gi_gj_gk_gl_ll_idxs[1152*8];
extern short bbus_gi_gj_gk_gl_ll_col_contr[1152*8];
extern float2 bbus_g5_gj_gjC_Cg5_ll_vals[768];
extern short bbus_g5_gj_gjC_Cg5_ll_idxs[768*8];
extern short bbus_g5_gj_gjC_Cg5_ll_col_contr[768*8];
extern float2 bbus_gj_g5_gjC_Cg5_ll_vals[768];
extern short bbus_gj_g5_gjC_Cg5_ll_idxs[768*8];
extern short bbus_gj_g5_gjC_Cg5_ll_col_contr[768*8];
extern float2 bbus_gi_gj_gkC_Cg5_ll_vals[768];
extern short bbus_gi_gj_gkC_Cg5_ll_idxs[768*8];
extern short bbus_gi_gj_gkC_Cg5_ll_col_contr[768*8];
extern float2 bbus_gjC_Cg5_g5_gj_ll_vals[768];
extern short bbus_gjC_Cg5_g5_gj_ll_idxs[768*8];
extern short bbus_gjC_Cg5_g5_gj_ll_col_contr[768*8];
extern float2 bbus_gjC_Cg5_gj_g5_ll_vals[768];
extern short bbus_gjC_Cg5_gj_g5_ll_idxs[768*8];
extern short bbus_gjC_Cg5_gj_g5_ll_col_contr[768*8];
extern float2 bbus_gkC_Cg5_gi_gj_ll_vals[768];
extern short bbus_gkC_Cg5_gi_gj_ll_idxs[768*8];
extern short bbus_gkC_Cg5_gi_gj_ll_col_contr[768*8];
extern float2 bbus_gjC_Cg5_gjC_Cg5_ll_vals[768];
extern short bbus_gjC_Cg5_gjC_Cg5_ll_idxs[768*8];
extern short bbus_gjC_Cg5_gjC_Cg5_ll_col_contr[768*8];
const std::vector<std::string> TETRA_prop_prods = {"udbb", "usbb"};
const std::vector<std::vector<std::string>> TETRA_prop_prods_names = {{"bbud/g5_gj_g5_gj_ll", "bbud/g5_gj_gj_g5_ll", "bbud/gj_g5_g5_gj_ll", "bbud/gj_g5_gj_g5_ll", "bbud/gi_gj_g5_gk_ll", "bbud/gi_gj_gk_g5_ll", "bbud/g5_gk_gi_gj_ll", "bbud/gk_g5_gi_gj_ll", "bbud/gi_gj_gk_gl_ll", "bbud/g5_gj_gjC_Cg5_ll", "bbud/gj_g5_gjC_Cg5_ll", "bbud/gi_gj_gkC_Cg5_ll", "bbud/gjC_Cg5_g5_gj_ll", "bbud/gjC_Cg5_gj_g5_ll", "bbud/gkC_Cg5_gi_gj_ll", "bbud/gjC_Cg5_gjC_Cg5_ll"}, {"bbus/g5_gj_g5_gj_ll", "bbus/g5_gj_gj_g5_ll", "bbus/gj_g5_g5_gj_ll", "bbus/gj_g5_gj_g5_ll", "bbus/gi_gj_g5_gk_ll", "bbus/gi_gj_gk_g5_ll", "bbus/g5_gk_gi_gj_ll", "bbus/gk_g5_gi_gj_ll", "bbus/gi_gj_gk_gl_ll", "bbus/g5_gj_gjC_Cg5_ll", "bbus/gj_g5_gjC_Cg5_ll", "bbus/gi_gj_gkC_Cg5_ll", "bbus/gjC_Cg5_g5_gj_ll", "bbus/gjC_Cg5_gj_g5_ll", "bbus/gkC_Cg5_gi_gj_ll", "bbus/gjC_Cg5_gjC_Cg5_ll"}};
const std::vector<std::vector<short>> TETRA_prop_prods_count = {{768, 768, 768, 768, 768, 768, 768, 768, 1152, 768, 768, 768, 768, 768, 768, 768}, {768, 768, 768, 768, 768, 768, 768, 768, 1152, 768, 768, 768, 768, 768, 768, 768}};
const std::vector<std::vector<short *>> TETRA_prop_prods_idxs = {{bbud_g5_gj_g5_gj_ll_idxs, bbud_g5_gj_gj_g5_ll_idxs, bbud_gj_g5_g5_gj_ll_idxs, bbud_gj_g5_gj_g5_ll_idxs, bbud_gi_gj_g5_gk_ll_idxs, bbud_gi_gj_gk_g5_ll_idxs, bbud_g5_gk_gi_gj_ll_idxs, bbud_gk_g5_gi_gj_ll_idxs, bbud_gi_gj_gk_gl_ll_idxs, bbud_g5_gj_gjC_Cg5_ll_idxs, bbud_gj_g5_gjC_Cg5_ll_idxs, bbud_gi_gj_gkC_Cg5_ll_idxs, bbud_gjC_Cg5_g5_gj_ll_idxs, bbud_gjC_Cg5_gj_g5_ll_idxs, bbud_gkC_Cg5_gi_gj_ll_idxs, bbud_gjC_Cg5_gjC_Cg5_ll_idxs}, {bbus_g5_gj_g5_gj_ll_idxs, bbus_g5_gj_gj_g5_ll_idxs, bbus_gj_g5_g5_gj_ll_idxs, bbus_gj_g5_gj_g5_ll_idxs, bbus_gi_gj_g5_gk_ll_idxs, bbus_gi_gj_gk_g5_ll_idxs, bbus_g5_gk_gi_gj_ll_idxs, bbus_gk_g5_gi_gj_ll_idxs, bbus_gi_gj_gk_gl_ll_idxs, bbus_g5_gj_gjC_Cg5_ll_idxs, bbus_gj_g5_gjC_Cg5_ll_idxs, bbus_gi_gj_gkC_Cg5_ll_idxs, bbus_gjC_Cg5_g5_gj_ll_idxs, bbus_gjC_Cg5_gj_g5_ll_idxs, bbus_gkC_Cg5_gi_gj_ll_idxs, bbus_gjC_Cg5_gjC_Cg5_ll_idxs}};
const std::vector<std::vector<float2 *>> TETRA_prop_prods_vals = {{bbud_g5_gj_g5_gj_ll_vals, bbud_g5_gj_gj_g5_ll_vals, bbud_gj_g5_g5_gj_ll_vals, bbud_gj_g5_gj_g5_ll_vals, bbud_gi_gj_g5_gk_ll_vals, bbud_gi_gj_gk_g5_ll_vals, bbud_g5_gk_gi_gj_ll_vals, bbud_gk_g5_gi_gj_ll_vals, bbud_gi_gj_gk_gl_ll_vals, bbud_g5_gj_gjC_Cg5_ll_vals, bbud_gj_g5_gjC_Cg5_ll_vals, bbud_gi_gj_gkC_Cg5_ll_vals, bbud_gjC_Cg5_g5_gj_ll_vals, bbud_gjC_Cg5_gj_g5_ll_vals, bbud_gkC_Cg5_gi_gj_ll_vals, bbud_gjC_Cg5_gjC_Cg5_ll_vals}, {bbus_g5_gj_g5_gj_ll_vals, bbus_g5_gj_gj_g5_ll_vals, bbus_gj_g5_g5_gj_ll_vals, bbus_gj_g5_gj_g5_ll_vals, bbus_gi_gj_g5_gk_ll_vals, bbus_gi_gj_gk_g5_ll_vals, bbus_g5_gk_gi_gj_ll_vals, bbus_gk_g5_gi_gj_ll_vals, bbus_gi_gj_gk_gl_ll_vals, bbus_g5_gj_gjC_Cg5_ll_vals, bbus_gj_g5_gjC_Cg5_ll_vals, bbus_gi_gj_gkC_Cg5_ll_vals, bbus_gjC_Cg5_g5_gj_ll_vals, bbus_gjC_Cg5_gj_g5_ll_vals, bbus_gkC_Cg5_gi_gj_ll_vals, bbus_gjC_Cg5_gjC_Cg5_ll_vals}};
const std::vector<std::vector<short *>> TETRA_prop_prods_col_contr = {{bbud_g5_gj_g5_gj_ll_col_contr, bbud_g5_gj_gj_g5_ll_col_contr, bbud_gj_g5_g5_gj_ll_col_contr, bbud_gj_g5_gj_g5_ll_col_contr, bbud_gi_gj_g5_gk_ll_col_contr, bbud_gi_gj_gk_g5_ll_col_contr, bbud_g5_gk_gi_gj_ll_col_contr, bbud_gk_g5_gi_gj_ll_col_contr, bbud_gi_gj_gk_gl_ll_col_contr, bbud_g5_gj_gjC_Cg5_ll_col_contr, bbud_gj_g5_gjC_Cg5_ll_col_contr, bbud_gi_gj_gkC_Cg5_ll_col_contr, bbud_gjC_Cg5_g5_gj_ll_col_contr, bbud_gjC_Cg5_gj_g5_ll_col_contr, bbud_gkC_Cg5_gi_gj_ll_col_contr, bbud_gjC_Cg5_gjC_Cg5_ll_col_contr}, {bbus_g5_gj_g5_gj_ll_col_contr, bbus_g5_gj_gj_g5_ll_col_contr, bbus_gj_g5_g5_gj_ll_col_contr, bbus_gj_g5_gj_g5_ll_col_contr, bbus_gi_gj_g5_gk_ll_col_contr, bbus_gi_gj_gk_g5_ll_col_contr, bbus_g5_gk_gi_gj_ll_col_contr, bbus_gk_g5_gi_gj_ll_col_contr, bbus_gi_gj_gk_gl_ll_col_contr, bbus_g5_gj_gjC_Cg5_ll_col_contr, bbus_gj_g5_gjC_Cg5_ll_col_contr, bbus_gi_gj_gkC_Cg5_ll_col_contr, bbus_gjC_Cg5_g5_gj_ll_col_contr, bbus_gjC_Cg5_gj_g5_ll_col_contr, bbus_gkC_Cg5_gi_gj_ll_col_contr, bbus_gjC_Cg5_gjC_Cg5_ll_col_contr}};
