/* This file had been generated by python/tetraquarks.py
 * 
 * The executed command has been:
 * python tetraquarks_stochastic_v3.py PLEGMA_bcud_tetraquarks_arrays_stoch.cuh PLEGMA_bcud_tetraquarks_arrays_stoch.cu
 * 
 * The gamma used are :
 * gx = [   0,  0,  0,  I,
 *          0,  0,  I,  0,
 *          0, -I,  0,  0,
 *         -I,  0,  0,  0, ] 
 * gy = [   0,  0,  0,  1,
 *          0,  0, -1,  0,
 *          0, -1,  0,  0,
 *          1,  0,  0,  0, ] 
 * gz = [   0,  0,  I,  0,
 *          0,  0,  0, -I,
 *         -I,  0,  0,  0,
 *          0,  I,  0,  0, ] 
 * gt = [   1,  0,  0,  0,
 *          0,  1,  0,  0,
 *          0,  0, -1,  0,
 *          0,  0,  0, -1, ] 
 *
 * bcud_J1 : {'flavs': ['bt^-up-ch^-dn', 'bt^-dn-ch^-up'], 'coeffs': [1, -1], 'spin': 1}
 * bcud_J0 : {'flavs': ['bt^-up-ch^-dn', 'bt^-dn-ch^-up'], 'coeffs': [1, -1], 'spin': 0}
 */
#pragma once
extern float2 bcud_J1_g5_g1_g5_g1_ls_vals[1024];
extern short bcud_J1_g5_g1_g5_g1_ls_idxs[1024*8];
extern short bcud_J1_g5_g1_g5_g1_ls_col_contr[1024*8];
extern float2 bcud_J1_g5_g2_g5_g2_ls_vals[1024];
extern short bcud_J1_g5_g2_g5_g2_ls_idxs[1024*8];
extern short bcud_J1_g5_g2_g5_g2_ls_col_contr[1024*8];
extern float2 bcud_J1_g5_g3_g5_g3_ls_vals[1024];
extern short bcud_J1_g5_g3_g5_g3_ls_idxs[1024*8];
extern short bcud_J1_g5_g3_g5_g3_ls_col_contr[1024*8];
extern float2 bcud_J1_g5_g1_g1_g5_ls_vals[1024];
extern short bcud_J1_g5_g1_g1_g5_ls_idxs[1024*8];
extern short bcud_J1_g5_g1_g1_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g5_g2_g2_g5_ls_vals[1024];
extern short bcud_J1_g5_g2_g2_g5_ls_idxs[1024*8];
extern short bcud_J1_g5_g2_g2_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g5_g3_g3_g5_ls_vals[1024];
extern short bcud_J1_g5_g3_g3_g5_ls_idxs[1024*8];
extern short bcud_J1_g5_g3_g3_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g1_g5_g5_g1_ls_vals[1024];
extern short bcud_J1_g1_g5_g5_g1_ls_idxs[1024*8];
extern short bcud_J1_g1_g5_g5_g1_ls_col_contr[1024*8];
extern float2 bcud_J1_g2_g5_g5_g2_ls_vals[1024];
extern short bcud_J1_g2_g5_g5_g2_ls_idxs[1024*8];
extern short bcud_J1_g2_g5_g5_g2_ls_col_contr[1024*8];
extern float2 bcud_J1_g3_g5_g5_g3_ls_vals[1024];
extern short bcud_J1_g3_g5_g5_g3_ls_idxs[1024*8];
extern short bcud_J1_g3_g5_g5_g3_ls_col_contr[1024*8];
extern float2 bcud_J1_g1_g5_g1_g5_ls_vals[1024];
extern short bcud_J1_g1_g5_g1_g5_ls_idxs[1024*8];
extern short bcud_J1_g1_g5_g1_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g2_g5_g2_g5_ls_vals[1024];
extern short bcud_J1_g2_g5_g2_g5_ls_idxs[1024*8];
extern short bcud_J1_g2_g5_g2_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g3_g5_g3_g5_ls_vals[1024];
extern short bcud_J1_g3_g5_g3_g5_ls_idxs[1024*8];
extern short bcud_J1_g3_g5_g3_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g2_g3_g5_g1_ls_x_vals[2048];
extern short bcud_J1_g2_g3_g5_g1_ls_x_idxs[2048*8];
extern short bcud_J1_g2_g3_g5_g1_ls_x_col_contr[2048*8];
extern float2 bcud_J1_g3_g1_g5_g2_ls_y_vals[2048];
extern short bcud_J1_g3_g1_g5_g2_ls_y_idxs[2048*8];
extern short bcud_J1_g3_g1_g5_g2_ls_y_col_contr[2048*8];
extern float2 bcud_J1_g1_g2_g5_g3_ls_z_vals[512];
extern short bcud_J1_g1_g2_g5_g3_ls_z_idxs[512*8];
extern short bcud_J1_g1_g2_g5_g3_ls_z_col_contr[512*8];
extern float2 bcud_J1_g2_g3_g1_g5_ls_x_vals[2048];
extern short bcud_J1_g2_g3_g1_g5_ls_x_idxs[2048*8];
extern short bcud_J1_g2_g3_g1_g5_ls_x_col_contr[2048*8];
extern float2 bcud_J1_g3_g1_g2_g5_ls_y_vals[2048];
extern short bcud_J1_g3_g1_g2_g5_ls_y_idxs[2048*8];
extern short bcud_J1_g3_g1_g2_g5_ls_y_col_contr[2048*8];
extern float2 bcud_J1_g1_g2_g3_g5_ls_z_vals[512];
extern short bcud_J1_g1_g2_g3_g5_ls_z_idxs[512*8];
extern short bcud_J1_g1_g2_g3_g5_ls_z_col_contr[512*8];
extern float2 bcud_J1_g5_g1_g2_g3_ls_x_vals[2048];
extern short bcud_J1_g5_g1_g2_g3_ls_x_idxs[2048*8];
extern short bcud_J1_g5_g1_g2_g3_ls_x_col_contr[2048*8];
extern float2 bcud_J1_g5_g2_g3_g1_ls_y_vals[2048];
extern short bcud_J1_g5_g2_g3_g1_ls_y_idxs[2048*8];
extern short bcud_J1_g5_g2_g3_g1_ls_y_col_contr[2048*8];
extern float2 bcud_J1_g5_g3_g1_g2_ls_z_vals[512];
extern short bcud_J1_g5_g3_g1_g2_ls_z_idxs[512*8];
extern short bcud_J1_g5_g3_g1_g2_ls_z_col_contr[512*8];
extern float2 bcud_J1_g1_g5_g2_g3_ls_x_vals[2048];
extern short bcud_J1_g1_g5_g2_g3_ls_x_idxs[2048*8];
extern short bcud_J1_g1_g5_g2_g3_ls_x_col_contr[2048*8];
extern float2 bcud_J1_g2_g5_g3_g1_ls_y_vals[2048];
extern short bcud_J1_g2_g5_g3_g1_ls_y_idxs[2048*8];
extern short bcud_J1_g2_g5_g3_g1_ls_y_col_contr[2048*8];
extern float2 bcud_J1_g3_g5_g1_g2_ls_z_vals[512];
extern short bcud_J1_g3_g5_g1_g2_ls_z_idxs[512*8];
extern short bcud_J1_g3_g5_g1_g2_ls_z_col_contr[512*8];
extern float2 bcud_J1_g2_g3_g2_g3_ls_x_vals[4096];
extern short bcud_J1_g2_g3_g2_g3_ls_x_idxs[4096*8];
extern short bcud_J1_g2_g3_g2_g3_ls_x_col_contr[4096*8];
extern float2 bcud_J1_g1_g3_g1_g3_ls_y_vals[4096];
extern short bcud_J1_g1_g3_g1_g3_ls_y_idxs[4096*8];
extern short bcud_J1_g1_g3_g1_g3_ls_y_col_contr[4096*8];
extern float2 bcud_J1_g1_g2_g1_g2_ls_z_vals[256];
extern short bcud_J1_g1_g2_g1_g2_ls_z_idxs[256*8];
extern short bcud_J1_g1_g2_g1_g2_ls_z_col_contr[256*8];
extern float2 bcud_J1_g1C_Cg5_g5_g1_ls_vals[1024];
extern short bcud_J1_g1C_Cg5_g5_g1_ls_idxs[1024*8];
extern short bcud_J1_g1C_Cg5_g5_g1_ls_col_contr[1024*8];
extern float2 bcud_J1_g2C_Cg5_g5_g2_ls_vals[1024];
extern short bcud_J1_g2C_Cg5_g5_g2_ls_idxs[1024*8];
extern short bcud_J1_g2C_Cg5_g5_g2_ls_col_contr[1024*8];
extern float2 bcud_J1_g3C_Cg5_g5_g3_ls_vals[1024];
extern short bcud_J1_g3C_Cg5_g5_g3_ls_idxs[1024*8];
extern short bcud_J1_g3C_Cg5_g5_g3_ls_col_contr[1024*8];
extern float2 bcud_J1_g1C_Cg5_g1_g5_ls_vals[1024];
extern short bcud_J1_g1C_Cg5_g1_g5_ls_idxs[1024*8];
extern short bcud_J1_g1C_Cg5_g1_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g2C_Cg5_g2_g5_ls_vals[1024];
extern short bcud_J1_g2C_Cg5_g2_g5_ls_idxs[1024*8];
extern short bcud_J1_g2C_Cg5_g2_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g3C_Cg5_g3_g5_ls_vals[1024];
extern short bcud_J1_g3C_Cg5_g3_g5_ls_idxs[1024*8];
extern short bcud_J1_g3C_Cg5_g3_g5_ls_col_contr[1024*8];
extern float2 bcud_J1_g1C_Cg5_g2_g3_ls_x_vals[2048];
extern short bcud_J1_g1C_Cg5_g2_g3_ls_x_idxs[2048*8];
extern short bcud_J1_g1C_Cg5_g2_g3_ls_x_col_contr[2048*8];
extern float2 bcud_J1_g2C_Cg5_g3_g1_ls_y_vals[2048];
extern short bcud_J1_g2C_Cg5_g3_g1_ls_y_idxs[2048*8];
extern short bcud_J1_g2C_Cg5_g3_g1_ls_y_col_contr[2048*8];
extern float2 bcud_J1_g3C_Cg5_g1_g2_ls_z_vals[512];
extern short bcud_J1_g3C_Cg5_g1_g2_ls_z_idxs[512*8];
extern short bcud_J1_g3C_Cg5_g1_g2_ls_z_col_contr[512*8];
extern float2 bcud_J0_g5_g5_g5_g5_ls_vals[1024];
extern short bcud_J0_g5_g5_g5_g5_ls_idxs[1024*8];
extern short bcud_J0_g5_g5_g5_g5_ls_col_contr[1024*8];
extern float2 bcud_J0_g5_g5_gj_gj_ls_vals[1536];
extern short bcud_J0_g5_g5_gj_gj_ls_idxs[1536*8];
extern short bcud_J0_g5_g5_gj_gj_ls_col_contr[1536*8];
extern float2 bcud_J0_gj_gj_g5_g5_ls_vals[1536];
extern short bcud_J0_gj_gj_g5_g5_ls_idxs[1536*8];
extern short bcud_J0_gj_gj_g5_g5_ls_col_contr[1536*8];
extern float2 bcud_J0_gj_gj_gk_gk_ls_vals[2304];
extern short bcud_J0_gj_gj_gk_gk_ls_idxs[2304*8];
extern short bcud_J0_gj_gj_gk_gk_ls_col_contr[2304*8];
extern float2 bcud_J0_g5C_Cg5_g5_g5_ls_vals[1024];
extern short bcud_J0_g5C_Cg5_g5_g5_ls_idxs[1024*8];
extern short bcud_J0_g5C_Cg5_g5_g5_ls_col_contr[1024*8];
extern float2 bcud_J0_g5C_Cg5_gj_gj_ls_vals[1536];
extern short bcud_J0_g5C_Cg5_gj_gj_ls_idxs[1536*8];
extern short bcud_J0_g5C_Cg5_gj_gj_ls_col_contr[1536*8];
const std::vector<std::string> TETRA_bcud_stoch_prop_prods = {"udcb"};
const std::vector<std::vector<std::string>> TETRA_bcud_stoch_prop_prods_names = {{"bcud_J1/g5_g1_g5_g1_ls", "bcud_J1/g5_g2_g5_g2_ls", "bcud_J1/g5_g3_g5_g3_ls", "bcud_J1/g5_g1_g1_g5_ls", "bcud_J1/g5_g2_g2_g5_ls", "bcud_J1/g5_g3_g3_g5_ls", "bcud_J1/g1_g5_g5_g1_ls", "bcud_J1/g2_g5_g5_g2_ls", "bcud_J1/g3_g5_g5_g3_ls", "bcud_J1/g1_g5_g1_g5_ls", "bcud_J1/g2_g5_g2_g5_ls", "bcud_J1/g3_g5_g3_g5_ls", "bcud_J1/g2_g3_g5_g1_ls_x", "bcud_J1/g3_g1_g5_g2_ls_y", "bcud_J1/g1_g2_g5_g3_ls_z", "bcud_J1/g2_g3_g1_g5_ls_x", "bcud_J1/g3_g1_g2_g5_ls_y", "bcud_J1/g1_g2_g3_g5_ls_z", "bcud_J1/g5_g1_g2_g3_ls_x", "bcud_J1/g5_g2_g3_g1_ls_y", "bcud_J1/g5_g3_g1_g2_ls_z", "bcud_J1/g1_g5_g2_g3_ls_x", "bcud_J1/g2_g5_g3_g1_ls_y", "bcud_J1/g3_g5_g1_g2_ls_z", "bcud_J1/g2_g3_g2_g3_ls_x", "bcud_J1/g1_g3_g1_g3_ls_y", "bcud_J1/g1_g2_g1_g2_ls_z", "bcud_J1/g1C_Cg5_g5_g1_ls", "bcud_J1/g2C_Cg5_g5_g2_ls", "bcud_J1/g3C_Cg5_g5_g3_ls", "bcud_J1/g1C_Cg5_g1_g5_ls", "bcud_J1/g2C_Cg5_g2_g5_ls", "bcud_J1/g3C_Cg5_g3_g5_ls", "bcud_J1/g1C_Cg5_g2_g3_ls_x", "bcud_J1/g2C_Cg5_g3_g1_ls_y", "bcud_J1/g3C_Cg5_g1_g2_ls_z", "bcud_J0/g5_g5_g5_g5_ls", "bcud_J0/g5_g5_gj_gj_ls", "bcud_J0/gj_gj_g5_g5_ls", "bcud_J0/gj_gj_gk_gk_ls", "bcud_J0/g5C_Cg5_g5_g5_ls", "bcud_J0/g5C_Cg5_gj_gj_ls"}};
const std::vector<std::vector<short>> TETRA_bcud_stoch_prop_prods_count = {{1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 2048, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 2048, 2048, 512, 4096, 4096, 256, 1024, 1024, 1024, 1024, 1024, 1024, 2048, 2048, 512, 1024, 1536, 1536, 2304, 1024, 1536}};
const std::vector<std::vector<short *>> TETRA_bcud_stoch_prop_prods_idxs = {{bcud_J1_g5_g1_g5_g1_ls_idxs, bcud_J1_g5_g2_g5_g2_ls_idxs, bcud_J1_g5_g3_g5_g3_ls_idxs, bcud_J1_g5_g1_g1_g5_ls_idxs, bcud_J1_g5_g2_g2_g5_ls_idxs, bcud_J1_g5_g3_g3_g5_ls_idxs, bcud_J1_g1_g5_g5_g1_ls_idxs, bcud_J1_g2_g5_g5_g2_ls_idxs, bcud_J1_g3_g5_g5_g3_ls_idxs, bcud_J1_g1_g5_g1_g5_ls_idxs, bcud_J1_g2_g5_g2_g5_ls_idxs, bcud_J1_g3_g5_g3_g5_ls_idxs, bcud_J1_g2_g3_g5_g1_ls_x_idxs, bcud_J1_g3_g1_g5_g2_ls_y_idxs, bcud_J1_g1_g2_g5_g3_ls_z_idxs, bcud_J1_g2_g3_g1_g5_ls_x_idxs, bcud_J1_g3_g1_g2_g5_ls_y_idxs, bcud_J1_g1_g2_g3_g5_ls_z_idxs, bcud_J1_g5_g1_g2_g3_ls_x_idxs, bcud_J1_g5_g2_g3_g1_ls_y_idxs, bcud_J1_g5_g3_g1_g2_ls_z_idxs, bcud_J1_g1_g5_g2_g3_ls_x_idxs, bcud_J1_g2_g5_g3_g1_ls_y_idxs, bcud_J1_g3_g5_g1_g2_ls_z_idxs, bcud_J1_g2_g3_g2_g3_ls_x_idxs, bcud_J1_g1_g3_g1_g3_ls_y_idxs, bcud_J1_g1_g2_g1_g2_ls_z_idxs, bcud_J1_g1C_Cg5_g5_g1_ls_idxs, bcud_J1_g2C_Cg5_g5_g2_ls_idxs, bcud_J1_g3C_Cg5_g5_g3_ls_idxs, bcud_J1_g1C_Cg5_g1_g5_ls_idxs, bcud_J1_g2C_Cg5_g2_g5_ls_idxs, bcud_J1_g3C_Cg5_g3_g5_ls_idxs, bcud_J1_g1C_Cg5_g2_g3_ls_x_idxs, bcud_J1_g2C_Cg5_g3_g1_ls_y_idxs, bcud_J1_g3C_Cg5_g1_g2_ls_z_idxs, bcud_J0_g5_g5_g5_g5_ls_idxs, bcud_J0_g5_g5_gj_gj_ls_idxs, bcud_J0_gj_gj_g5_g5_ls_idxs, bcud_J0_gj_gj_gk_gk_ls_idxs, bcud_J0_g5C_Cg5_g5_g5_ls_idxs, bcud_J0_g5C_Cg5_gj_gj_ls_idxs}};
const std::vector<std::vector<float2 *>> TETRA_bcud_stoch_prop_prods_vals = {{bcud_J1_g5_g1_g5_g1_ls_vals, bcud_J1_g5_g2_g5_g2_ls_vals, bcud_J1_g5_g3_g5_g3_ls_vals, bcud_J1_g5_g1_g1_g5_ls_vals, bcud_J1_g5_g2_g2_g5_ls_vals, bcud_J1_g5_g3_g3_g5_ls_vals, bcud_J1_g1_g5_g5_g1_ls_vals, bcud_J1_g2_g5_g5_g2_ls_vals, bcud_J1_g3_g5_g5_g3_ls_vals, bcud_J1_g1_g5_g1_g5_ls_vals, bcud_J1_g2_g5_g2_g5_ls_vals, bcud_J1_g3_g5_g3_g5_ls_vals, bcud_J1_g2_g3_g5_g1_ls_x_vals, bcud_J1_g3_g1_g5_g2_ls_y_vals, bcud_J1_g1_g2_g5_g3_ls_z_vals, bcud_J1_g2_g3_g1_g5_ls_x_vals, bcud_J1_g3_g1_g2_g5_ls_y_vals, bcud_J1_g1_g2_g3_g5_ls_z_vals, bcud_J1_g5_g1_g2_g3_ls_x_vals, bcud_J1_g5_g2_g3_g1_ls_y_vals, bcud_J1_g5_g3_g1_g2_ls_z_vals, bcud_J1_g1_g5_g2_g3_ls_x_vals, bcud_J1_g2_g5_g3_g1_ls_y_vals, bcud_J1_g3_g5_g1_g2_ls_z_vals, bcud_J1_g2_g3_g2_g3_ls_x_vals, bcud_J1_g1_g3_g1_g3_ls_y_vals, bcud_J1_g1_g2_g1_g2_ls_z_vals, bcud_J1_g1C_Cg5_g5_g1_ls_vals, bcud_J1_g2C_Cg5_g5_g2_ls_vals, bcud_J1_g3C_Cg5_g5_g3_ls_vals, bcud_J1_g1C_Cg5_g1_g5_ls_vals, bcud_J1_g2C_Cg5_g2_g5_ls_vals, bcud_J1_g3C_Cg5_g3_g5_ls_vals, bcud_J1_g1C_Cg5_g2_g3_ls_x_vals, bcud_J1_g2C_Cg5_g3_g1_ls_y_vals, bcud_J1_g3C_Cg5_g1_g2_ls_z_vals, bcud_J0_g5_g5_g5_g5_ls_vals, bcud_J0_g5_g5_gj_gj_ls_vals, bcud_J0_gj_gj_g5_g5_ls_vals, bcud_J0_gj_gj_gk_gk_ls_vals, bcud_J0_g5C_Cg5_g5_g5_ls_vals, bcud_J0_g5C_Cg5_gj_gj_ls_vals}};
const std::vector<std::vector<short *>> TETRA_bcud_stoch_prop_prods_col_contr = {{bcud_J1_g5_g1_g5_g1_ls_col_contr, bcud_J1_g5_g2_g5_g2_ls_col_contr, bcud_J1_g5_g3_g5_g3_ls_col_contr, bcud_J1_g5_g1_g1_g5_ls_col_contr, bcud_J1_g5_g2_g2_g5_ls_col_contr, bcud_J1_g5_g3_g3_g5_ls_col_contr, bcud_J1_g1_g5_g5_g1_ls_col_contr, bcud_J1_g2_g5_g5_g2_ls_col_contr, bcud_J1_g3_g5_g5_g3_ls_col_contr, bcud_J1_g1_g5_g1_g5_ls_col_contr, bcud_J1_g2_g5_g2_g5_ls_col_contr, bcud_J1_g3_g5_g3_g5_ls_col_contr, bcud_J1_g2_g3_g5_g1_ls_x_col_contr, bcud_J1_g3_g1_g5_g2_ls_y_col_contr, bcud_J1_g1_g2_g5_g3_ls_z_col_contr, bcud_J1_g2_g3_g1_g5_ls_x_col_contr, bcud_J1_g3_g1_g2_g5_ls_y_col_contr, bcud_J1_g1_g2_g3_g5_ls_z_col_contr, bcud_J1_g5_g1_g2_g3_ls_x_col_contr, bcud_J1_g5_g2_g3_g1_ls_y_col_contr, bcud_J1_g5_g3_g1_g2_ls_z_col_contr, bcud_J1_g1_g5_g2_g3_ls_x_col_contr, bcud_J1_g2_g5_g3_g1_ls_y_col_contr, bcud_J1_g3_g5_g1_g2_ls_z_col_contr, bcud_J1_g2_g3_g2_g3_ls_x_col_contr, bcud_J1_g1_g3_g1_g3_ls_y_col_contr, bcud_J1_g1_g2_g1_g2_ls_z_col_contr, bcud_J1_g1C_Cg5_g5_g1_ls_col_contr, bcud_J1_g2C_Cg5_g5_g2_ls_col_contr, bcud_J1_g3C_Cg5_g5_g3_ls_col_contr, bcud_J1_g1C_Cg5_g1_g5_ls_col_contr, bcud_J1_g2C_Cg5_g2_g5_ls_col_contr, bcud_J1_g3C_Cg5_g3_g5_ls_col_contr, bcud_J1_g1C_Cg5_g2_g3_ls_x_col_contr, bcud_J1_g2C_Cg5_g3_g1_ls_y_col_contr, bcud_J1_g3C_Cg5_g1_g2_ls_z_col_contr, bcud_J0_g5_g5_g5_g5_ls_col_contr, bcud_J0_g5_g5_gj_gj_ls_col_contr, bcud_J0_gj_gj_g5_g5_ls_col_contr, bcud_J0_gj_gj_gk_gk_ls_col_contr, bcud_J0_g5C_Cg5_g5_g5_ls_col_contr, bcud_J0_g5C_Cg5_gj_gj_ls_col_contr}};
