#include <PLEGMA_Correlator.h>
#include <PLEGMA_Gauge.h>
#include "PLEGMA_kernel_utils.cuh"
#include "PLEGMA_kernel_getSet.cuh"
#include "PLEGMA_gammas.cuh"
#include "PLEGMA_threep.cuh"
#include <PLEGMA_Vector.h>
#include <malloc_quda.h>
using namespace plegma;
template<typename T>
struct KernelArr {T* array; int size;};

template<bool b, typename FloatA> using local_PorV = typename std::conditional< b==true,  Float2<FloatA>[N_SPINS][N_SPINS][N_COLS][N_COLS],  Float2<FloatA>[N_SPINS][N_COLS]>::type;

template<bool b, typename FloatA> using PorV = typename std::conditional< b==true,  PLEGMA_Propagator<FloatA>&,  PLEGMA_Vector<FloatA>&>::type;

template<bool b, typename FloatA> using PorVtex = typename std::conditional< b==true,  propTex<FloatA>,  vectorTex<FloatA>>::type;



template<bool b,typename FloatC, typename FloatA, typename FloatB, typename FloatG>
__global__ void threep_threeD_part1_device(Float2<FloatC>* block2,
                                   typename std::conditional<b==true, propTex<FloatA>,  vectorTex<FloatA>>::type texture1,
                                   typename std::conditional<b==true, propTex<FloatB>,  vectorTex<FloatB>>::type texture2,
				   gaugeTex<FloatG> gaugeTex, KernelArr<GAMMAS> listGammas,
				   int it, int time_step, int maxT, int4 source,
				   int signProps, bool runFT, tex_mom_list moms,
				   int dir1, int dir2, int dir3, int mu, int nu, int c1, int c2){
  int grid3D = gridDim.x/time_step;
  int sid3D = (blockIdx.x % grid3D)*blockDim.x + threadIdx.x;
  int tid = blockIdx.x/grid3D;
  // this takes into account the case where the source is in the local lattice
  // and we need to start from it when we go over maxT
  int t=it+tid; if(t>=maxT) t=(source.w%DGC_localL[DIM_T])+t-maxT;
  int vid = sid3D + t*DGC_localVolume3D;
  bool notZfac = (mu<0) && (nu<0) && (c1<0) && (c2<0);
  
  Float2<FloatC> accum[N_SPINS*N_SPINS];
  #pragma unroll
  for(int i = 0; i < N_SPINS*N_SPINS; i++)
    accum[i]=0;

  if (sid3D < DGC_localVolume3D){
    local_PorV<b,FloatA> prop1;
    local_PorV<b,FloatB> prop2;

    Float2<FloatC> R[N_SPINS][N_SPINS];
    Float2<FloatG> su3_1[N_COLS][N_COLS];
    Float2<FloatG> su3_2[N_COLS][N_COLS];
    Float2<FloatG> su3_3[N_COLS][N_COLS];
#if 0	  
    // BEGIN REGION
    // This has been generated by python/generate_derivative.py
    // The order has been optmized such that 70 data accesses have been commented out
    // + term x, x, x+dir1, x+dir1+dir2, x+dir1+dir2+dir3
    texture1.get(prop1,vid); gaugeTex.get(su3_1,dir1,vid); gaugeTex.get<Plus>(su3_2,dir2,vid,dir1); gaugeTex.get<PlusPlus>(su3_3,dir3,vid,dir1,dir2); texture2.get<PlusPlusPlus>(prop2,vid,dir1,dir2,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ZERO_PLUS,false,false,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x, x, x+dir1, x+dir1+dir2-dir3^, x+dir1+dir2-dir3
    /*texture1.get(prop1,vid);*/ /*gaugeTex.get(su3_1,dir1,vid);*/ /*gaugeTex.get<Plus>(su3_2,dir2,vid,dir1);*/ gaugeTex.get<PlusPlusMinus>(su3_3,dir3,vid,dir1,dir2,dir3); texture2.get<PlusPlusMinus>(prop2,vid,dir1,dir2,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,false,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x+dir3, x+dir3, x+dir1+dir3, x+dir1+dir2^, x+dir1+dir2
    texture1.get<Plus>(prop1,vid,dir3); gaugeTex.get<Plus>(su3_1,dir1,vid,dir3); gaugeTex.get<PlusPlus>(su3_2,dir2,vid,dir1,dir3); gaugeTex.get<PlusPlus>(su3_3,dir3,vid,dir1,dir2); texture2.get<PlusPlus>(prop2,vid,dir1,dir2);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,false,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x-dir3, x-dir3, x+dir1-dir3, x+dir1+dir2-dir3, x+dir1+dir2
    texture1.get<Minus>(prop1,vid,dir3); gaugeTex.get<Minus>(su3_1,dir1,vid,dir3); gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir3); gaugeTex.get<PlusPlusMinus>(su3_3,dir3,vid,dir1,dir2,dir3); /*texture2.get<PlusPlus>(prop2,vid,dir1,dir2);*/
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,false,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x, x, x+dir1-dir2^, x+dir1-dir2, x+dir1-dir2+dir3
    texture1.get(prop1,vid); gaugeTex.get(su3_1,dir1,vid); gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir2); gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir2); texture2.get<PlusMinusPlus>(prop2,vid,dir1,dir2,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,true,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x, x, x+dir1-dir2^, x+dir1-dir2-dir3^, x+dir1-dir2-dir3
    /*texture1.get(prop1,vid);*/ /*gaugeTex.get(su3_1,dir1,vid);*/ /*gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir2);*/ gaugeTex.get<PlusMinusMinus>(su3_3,dir3,vid,dir1,dir2,dir3); texture2.get<PlusMinusMinus>(prop2,vid,dir1,dir2,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,true,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x+dir3, x+dir3, x+dir1-dir2+dir3^, x+dir1-dir2^, x+dir1-dir2
    texture1.get<Plus>(prop1,vid,dir3); gaugeTex.get<Plus>(su3_1,dir1,vid,dir3); gaugeTex.get<PlusMinusPlus>(su3_2,dir2,vid,dir1,dir2,dir3); gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir2); texture2.get<PlusMinus>(prop2,vid,dir1,dir2);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,true,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x-dir3, x-dir3, x+dir1-dir2-dir3^, x+dir1-dir2-dir3, x+dir1-dir2
    texture1.get<Minus>(prop1,vid,dir3); gaugeTex.get<Minus>(su3_1,dir1,vid,dir3); gaugeTex.get<PlusMinusMinus>(su3_2,dir2,vid,dir1,dir2,dir3); gaugeTex.get<PlusMinusMinus>(su3_3,dir3,vid,dir1,dir2,dir3); /*texture2.get<PlusMinus>(prop2,vid,dir1,dir2);*/
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,true,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x+dir2, x+dir2, x+dir1^, x+dir1, x+dir1+dir3
    texture1.get<Plus>(prop1,vid,dir2); gaugeTex.get<Plus>(su3_1,dir1,vid,dir2); gaugeTex.get<Plus>(su3_2,dir2,vid,dir1); gaugeTex.get<Plus>(su3_3,dir3,vid,dir1); texture2.get<PlusPlus>(prop2,vid,dir1,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,true,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x+dir2, x+dir2, x+dir1^, x+dir1-dir3^, x+dir1-dir3
    /*texture1.get<Plus>(prop1,vid,dir2);*/ /*gaugeTex.get<Plus>(su3_1,dir1,vid,dir2);*/ /*gaugeTex.get<Plus>(su3_2,dir2,vid,dir1);*/ gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir3); texture2.get<PlusMinus>(prop2,vid,dir1,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,true,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x+dir2+dir3, x+dir2+dir3, x+dir1+dir3^, x+dir1^, x+dir1
    texture1.get<PlusPlus>(prop1,vid,dir2,dir3); gaugeTex.get<PlusPlus>(su3_1,dir1,vid,dir2,dir3); gaugeTex.get<PlusPlus>(su3_2,dir2,vid,dir1,dir3); gaugeTex.get<Plus>(su3_3,dir3,vid,dir1); texture2.get<Plus>(prop2,vid,dir1);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,true,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x+dir2-dir3, x+dir2-dir3, x+dir1-dir3^, x+dir1-dir3, x+dir1
    texture1.get<PlusMinus>(prop1,vid,dir2,dir3); gaugeTex.get<PlusMinus>(su3_1,dir1,vid,dir2,dir3); gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir3); gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir3); /*texture2.get<Plus>(prop2,vid,dir1);*/
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,true,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x-dir2, x-dir2, x+dir1-dir2, x+dir1, x+dir1+dir3
    texture1.get<Minus>(prop1,vid,dir2); gaugeTex.get<Minus>(su3_1,dir1,vid,dir2); gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir2); gaugeTex.get<Plus>(su3_3,dir3,vid,dir1); texture2.get<PlusPlus>(prop2,vid,dir1,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,false,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x-dir2, x-dir2, x+dir1-dir2, x+dir1-dir3^, x+dir1-dir3
    /*texture1.get<Minus>(prop1,vid,dir2);*/ /*gaugeTex.get<Minus>(su3_1,dir1,vid,dir2);*/ /*gaugeTex.get<PlusMinus>(su3_2,dir2,vid,dir1,dir2);*/ gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir3); texture2.get<PlusMinus>(prop2,vid,dir1,dir3);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,false,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // - term x-dir2+dir3, x-dir2+dir3, x+dir1-dir2+dir3, x+dir1^, x+dir1
    texture1.get<MinusPlus>(prop1,vid,dir2,dir3); gaugeTex.get<MinusPlus>(su3_1,dir1,vid,dir2,dir3); gaugeTex.get<PlusMinusPlus>(su3_2,dir2,vid,dir1,dir2,dir3); gaugeTex.get<Plus>(su3_3,dir3,vid,dir1); texture2.get<Plus>(prop2,vid,dir1);
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_MINUS,false,false,true>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);

    // + term x-dir2-dir3, x-dir2-dir3, x+dir1-dir2-dir3, x+dir1-dir3, x+dir1
    texture1.get<MinusMinus>(prop1,vid,dir2,dir3); gaugeTex.get<MinusMinus>(su3_1,dir1,vid,dir2,dir3); gaugeTex.get<PlusMinusMinus>(su3_2,dir2,vid,dir1,dir2,dir3); gaugeTex.get<PlusMinus>(su3_3,dir3,vid,dir1,dir3); /*texture2.get<Plus>(prop2,vid,dir1);*/
    partial_trace_mul_Prop_G1_G2_G3_Prop<true,ACC_PLUS,false,false,false>(R,prop1,prop2,su3_1,su3_2,su3_3,mu,nu,c1,c2);
#endif
	
    for(int iop = 0; iop < listGammas.size; iop++){
      int opId=listGammas.array[iop];
      if(notZfac) {
        if (signProps >0){
          accum[iop]= 0.015625*trace_gamma_S<true>(opId,TMP,R);
        }
        else if (signProps<0){
          accum[iop]= 0.015625*trace_gamma_S<true>(opId,TMM,R);
        }
        else{
          accum[iop]=0.015625*trace_gamma_S<true>(opId,NOROT,R);
        }
      }
      else accum[iop] = trace_gamma_S<true>(opId,NOROT,R);
    }
  }    

  int site_size = listGammas.size;
  int source_pos[3] = {source.x, source.y, source.z}; 
  if(runFT){
    extern __shared__ int ext_shared_cache[];
    Float2<FloatC> *shared_cache = (Float2<FloatC> *) ext_shared_cache;
    fourier_transform_3D(block2, accum, shared_cache, site_size, sid3D, source_pos, moms, 0, +1, time_step, tid);
  } else{
    if (sid3D < DGC_localVolume3D)
      for(int iop = 0; iop < site_size; iop++)
	block2[(tid*DGC_localVolume3D + sid3D)*site_size+iop] = accum[iop];
  }
}

template<bool b, typename FloatC,typename FloatA, typename FloatB, typename FloatG>
static void threep_threeD_part1_host(ProfileStruct &ps, Float2<FloatC> *result, PLEGMA_Correlator<FloatC> &corr,
                              PorV<b, FloatA> &prop1,
                              PorV<b, FloatB> &prop2,
			      int signProps, PLEGMA_Gauge<FloatG>& gauge, std::vector<GAMMAS>& gammas, bool isZfac){
  
  int t_size = corr.localT(); if(t_size==0) return;
  int maxT = corr.endT() - corr.startT(); 
  int time_step = get_time_step(ps.tp.grid.x, ps.tp.block.x);
  bool runFT = (corr.getCorrSpace() == MOMENTUM_SPACE);
  size_t volume = corr.getVolSize()/t_size;
  int extra=N_DIMS*(N_DIMS-1)*(N_DIMS-2);
  if(isZfac) extra*=N_SPINS*N_SPINS*N_COLS*N_COLS;
  size_t size = corr.getTotalSize()/extra/t_size*time_step;
  int site_size = corr.getSiteSize()/extra;
  int4 source = corr.getSource();
  auto moms = corr.getTexMomList();

  KernelArr<GAMMAS> listGammas;
  listGammas.size = gammas.size();
//  cudaMalloc((void**)&listGammas.array, gammas.size()*sizeof(GAMMAS));
  listGammas.array=(GAMMAS*)device_malloc(gammas.size()*sizeof(GAMMAS));
  qudaMemcpy(listGammas.array, gammas.data(), gammas.size()*sizeof(GAMMAS), qudaMemcpyHostToDevice);

  if(HGC_verbosity > 2)
    if(corr.hasSource())
      printf("time_step = %d, t_size = %d, maxT = %d, ps.tp.grid.x = %d, ps.tp.block.x = %d, ps.tp.shared_bytes = %d\n", time_step, t_size, maxT, ps.tp.grid.x, ps.tp.block.x, ps.tp.shared_bytes);

  size_t alloc_size = (runFT==true)? (size * (ps.tp.grid.x/time_step) ) : size;

  Float2<FloatC> *h_partial_block = NULL;
  Float2<FloatC> *d_partial_block = NULL;
//  cudaMalloc((void**)&d_partial_block, alloc_size * sizeof(Float2<FloatC>) );
  d_partial_block=(Float2<FloatC> *)device_malloc(alloc_size*sizeof(Float2<FloatC>));
  hostMalloc(h_partial_block, alloc_size*sizeof(Float2<FloatC>));

  auto propTex1 = toTexture<PorVtex<b,FloatA>>(prop1);
  auto propTex2 = toTexture<PorVtex<b,FloatB>>(prop2);
  auto gaugetex = toTexture<gaugeTex>(gauge);

//  cudaError_t error=cudaPeekAtLastError();
//  if(error != cudaSuccess || h_partial_block==NULL) goto exit;
  for(int it=0; it < t_size; it+=time_step) {
    for(int et=0; et < extra; et++) {
      int dir1 = (et/(N_DIMS-1)/(N_DIMS-2)) % N_DIMS;
      int dir2 = (et/(N_DIMS-2)) % (N_DIMS-1);
      int dir3 = et % (N_DIMS-2);
      if(dir2>=dir1) dir2++;
      if(dir3>=dir1){
	dir3++;
	if(dir3>=dir2)
	  dir3++;
      } else if(dir3>=dir2){
	dir3++;
	if(dir3>=dir1)
	  dir3++;
      }

      int mu=-1, nu=-1, c1=-1, c2=-1;
      if(isZfac) {
	int tt = et/N_DIMS/(N_DIMS-1)/(N_DIMS-2);
	mu=tt/N_SPINS/N_COLS/N_COLS;
	nu=(tt/N_COLS/N_COLS)%N_SPINS;
	c1=(tt/N_COLS)%N_COLS;
	c2=tt%N_COLS;
      }	
      int t_step = std::min(t_size-it, time_step);
      dim3 grid = ps.tp.grid;
      grid.x = (grid.x/time_step)*t_step;
      threep_threeD_part1_device<b,FloatC,FloatA, FloatB, FloatG>
	<<<grid,ps.tp.block,ps.tp.shared_bytes>>>
	(d_partial_block, *propTex1, *propTex2, *gaugetex, listGammas, it, t_step, maxT,
	 source, signProps, runFT, *moms, dir1,dir2,dir3,mu,nu,c1,c2);
//      error=cudaPeekAtLastError(); if(error != cudaSuccess) goto exit;
      
      qudaMemcpy(h_partial_block, d_partial_block, (alloc_size/time_step)*t_step*sizeof(Float2<FloatC>), qudaMemcpyDeviceToHost);
//      error=cudaPeekAtLastError(); if(error != cudaSuccess) goto exit;
      
      if(runFT==true){
	int accumX = ps.tp.grid.x/time_step;
	for(size_t v = 0 ; v < volume*t_step; v++)
	  for(int i = 0 ; i < site_size; i++) {
	    result[((it*volume+v)*extra+et)*site_size+i] = 0;
	    for(int j = 0 ; j < accumX; j++)
	      result[((it*volume+v)*extra+et)*site_size+i] +=
		h_partial_block[(v*site_size+i)*accumX+j];
	  }
      } else {
	for(size_t v = 0 ; v < volume*t_step; v++)
	  for(int i = 0 ; i < site_size; i++)
	    result[((it*volume+v)*extra+et)*site_size+i] =
	      h_partial_block[v*site_size+i];
      }
    }
  }
  
 exit:
  hostFree(h_partial_block, alloc_size*sizeof(FloatC));
  device_free(d_partial_block);
  device_free(listGammas.array);
}

template<bool b, typename FloatC,typename FloatA,typename FloatB,typename FloatG>
void threep_threeD_part1(PLEGMA_Correlator<FloatC> &corr, 
		typename std::conditional<b==true, PLEGMA_Propagator<FloatA>&, PLEGMA_Vector<FloatA>&>::type prop1,
                typename std::conditional<b==true, PLEGMA_Propagator<FloatB>&, PLEGMA_Vector<FloatB>&>::type prop2,
		 int signProps, PLEGMA_Gauge<FloatG>& gauge, std::vector<GAMMAS>& gammas, bool isZfac){
#ifdef PLEGMA_NUCLEON_3PF_FIX_SINK
  if(gammas.size() <= 0)
    PLEGMA_error("Error the container of gamma matrices cannot be zero");
  if(gammas.size() > N_SPINS*N_SPINS)
    PLEGMA_error("Error maximum number of gamma matrices is 16");

  bool runFT = (corr.getCorrSpace() == MOMENTUM_SPACE);
  int site_size = N_DIMS*(N_DIMS-1)*(N_DIMS-2)*gammas.size();
  
  if(isZfac)
    site_size *= N_SPINS*N_SPINS*N_COLS*N_COLS;
  
  if(corr.getSiteSize() != site_size)
    PLEGMA_error("Correlator siteSize do not match: %d != %d\n", corr.getSiteSize(), site_size);

  site_size = gammas.size();
  ProfileStruct ps(HGC_localVolume3D, (runFT==true) ? site_size*sizeof(Float2<FloatC>) : 0);
  int myLocalT = corr.localT();
  int maxLocalT = myLocalT;
  MPI_Allreduce( &myLocalT, &maxLocalT, 1, MPI_Type(maxLocalT), MPI_MAX, HGC_fullComm);
  ps.max_volume = HGC_localVolume3D*maxLocalT;
  ps.tune_globally = true;
  
  Float2<FloatC> *result = (Float2<FloatC> *) corr.H_elem();

  tune( ps, "threep_threeD", threep_threeD_part1_host<b,FloatC,FloatA,FloatB,FloatG>,
	ps, result, corr, prop1, prop2, signProps, gauge, gammas,false);
  run( ps, "threep_threeD", threep_threeD_part1_host<b,FloatC,FloatA,FloatB,FloatG>,
       ps, result, corr, prop1, prop2, signProps, gauge, gammas,isZfac);

#else
  PLEGMA_error("You must enable PLEGMA_NUCLEON_3PF_FIX_SINK\n");
#endif
}

template void threep_threeD_part1<true,float,float,float,float>(PLEGMA_Correlator<float> &corr, PLEGMA_Propagator<float>& prop1, PLEGMA_Propagator<float>& prop2, int signProps, PLEGMA_Gauge<float>& gauge, std::vector<GAMMAS>& gammas, bool isZfac);
template void threep_threeD_part1<true,double,double,double,double>(PLEGMA_Correlator<double> &corr, PLEGMA_Propagator<double>& prop1, PLEGMA_Propagator<double>& prop2, int signProps, PLEGMA_Gauge<double>& gauge, std::vector<GAMMAS>& gammas, bool isZfac);

template void threep_threeD_part1<false,float,float,float,float>(PLEGMA_Correlator<float> &corr, PLEGMA_Vector<float>& prop1, PLEGMA_Vector<float>& prop2, int signProps, PLEGMA_Gauge<float>& gauge, std::vector<GAMMAS>& gammas, bool isZfac);
template void threep_threeD_part1<false,double,double,double,double>(PLEGMA_Correlator<double> &corr, PLEGMA_Vector<double>& prop1, PLEGMA_Vector<double>& prop2, int signProps, PLEGMA_Gauge<double>& gauge, std::vector<GAMMAS>& gammas, bool isZfac);
