from itertools import permutations, product
import sys

N = int(sys.argv[1])

dirs = (+1, -1, +2, -2)


def get_sign(i):
    if i > 0:
        return "+"
    if i < 0:
        return "-"
    return ""


def get_pos(pos):
    x = "x"
    for d, v in enumerate(pos):
        if v == 0:
            continue
        x += get_sign(v) + (f"dir{d+1}" if N > 1 else "dir")
    return x


def get_tab():
    return "  " * (N + 2)


def get_comment(sign, left, gauge, dagger, right):
    cmt = get_tab() + "// " + get_sign(sign) + " term "
    cmt += get_pos(left) + ", "
    cmt += (
        ", ".join((get_pos(g) + ("^" if d else "") for g, d in zip(gauge, dagger)))
        + ", "
    )
    cmt += get_pos(right)
    return cmt


def get_shift(pos):
    shift = ""
    for v in pos:
        if v == 0:
            continue
        shift += "Plus" if v > 0 else "Minus"
    if shift:
        return "<" + shift + ">"
    return ""


def get_dirs(pos):
    dirs = ""
    for d, v in enumerate(pos):
        if v == 0:
            continue
        dirs += ",dir%d" % (d + 1) if N > 1 else ",dir"
    return dirs


COMMENTED = 0


def comment(line, left, right):
    global COMMENTED
    if left == right:
        COMMENTED += 1
        return "/*" + line + "*/"
    return line


def get_data_line(left, gauge, right, old=None):
    line = get_tab()
    line += (
        comment(
            f"prop1Tex.get{get_shift(left)}(prop1,vid{get_dirs(left)});",
            left,
            old[0] if old else None,
        )
        + " "
    )
    for i, g in enumerate(gauge):
        line += (
            comment(
                f"gaugeTex.get{get_shift(g)}(su3_{i+1},dir{i+1},vid{get_dirs(g)});"
                if N > 1
                else "gaugeTex.get{get_shift(g)}(su3,dir,vid{get_dirs(g)});",
                g,
                old[1][i] if old else None,
            )
            + " "
        )
    line += comment(
        f"prop2Tex.get{get_shift(right)}(prop2,vid{get_dirs(right)});",
        right,
        old[-1] if old else None,
    )
    return line


def get_comp_line(sign, dagger, first):
    line = get_tab()
    line += "partial_trace_mul_Prop_"
    line += "_".join((f"G{i+1}" for i in range(N))) if N > 1 else "G"
    line += (
        "_Prop<true,"
        + ("ZERO_" if first else "ACC_")
        + ("MINUS," if sign < 0 else "PLUS,")
    )
    line += ",".join(("true" if d else "false" for d in dagger))
    line += ">(R,prop1,prop2,"
    line += ",".join((f"su3_{i+1}" for i in range(N))) if N > 1 else "su3"
    line += ",mu,nu,c1,c2);"
    return line


best = -1
MAX = 10000
order = None
for perm in permutations(product(*([dirs] * N))):
    old = None
    COMMENTED = 0
    text = []
    for n, term in enumerate(perm):
        sign = 1
        left = [0] * N
        right = [0] * N
        for i, lr in enumerate(term):
            if lr == -1 or lr == 2:
                sign *= -1
            if abs(lr) == 2:
                left[i] += +1 if lr > 0 else -1
            else:
                right[i] += +1 if lr > 0 else -1

        last = left
        gauge = []
        dagger = []
        for i, lr in enumerate(term):
            cur = list(last)
            nxt = list(last)
            if abs(lr) == 2:
                nxt[i] += -1 if lr > 0 else +1
                if lr > 0:
                    cur[i] += -1
                    dagger.append(True)
                else:
                    dagger.append(False)
            elif abs(lr) == 1:
                nxt[i] += +1 if lr > 0 else -1
                if lr < 0:
                    cur[i] += -1
                    dagger.append(True)
                else:
                    dagger.append(False)

            gauge.append(cur)
            last = nxt

        text.append(get_comment(sign, left, gauge, dagger, right))
        text.append(get_data_line(left, gauge, right, old))
        text.append(get_comp_line(sign, dagger, True if n == 0 else False))
        text.append("")
        old = [left, gauge, right]

    if COMMENTED > best:
        output = text
        best = COMMENTED
    MAX -= 1
    if MAX < 0:
        break

print(get_tab() + "// BEGIN REGION")
print(get_tab() + "// This has been generated by python/generate_derivative.py")
print(
    get_tab()
    + f"// The order has been optmized such that {best} data accesses have been commented out"
)
print("\n".join(output))
print(get_tab() + "// END REGION")
