#pragma once
/* This file had been generated by baryons.py
 * 
 * The executed command has been:
 * python python/baryons.py include/PLEGMA_all_baryons.h lib/kernels/PLEGMA_all_baryons_arrays.cuh
 * 
 * The gamma used are :
 * gx = [   0,  0,  0,  I,
 *          0,  0,  I,  0,
 *          0, -I,  0,  0,
 *         -I,  0,  0,  0, ] 
 * gy = [   0,  0,  0,  1,
 *          0,  0, -1,  0,
 *          0, -1,  0,  0,
 *          1,  0,  0,  0, ] 
 * gz = [   0,  0,  I,  0,
 *          0,  0,  0, -I,
 *         -I,  0,  0,  0,
 *          0,  I,  0,  0, ] 
 * gt = [   1,  0,  0,  0,
 *          0,  1,  0,  0,
 *          0,  0, -1,  0,
 *          0,  0,  0, -1, ] 
 *
 * Xicc++ : {'flavs': ['ch-up-ch'], 'coeffs': [1], 'spin': 0.5}
 * Xicc+ : {'flavs': ['ch-dn-ch'], 'coeffs': [1], 'spin': 0.5}
 * Omegacc+ : {'flavs': ['ch-sr-ch'], 'coeffs': [1], 'spin': 0.5}
 * Sigmac++ : {'flavs': ['up-ch-up'], 'coeffs': [1], 'spin': 0.5}
 * Sigmac+ : {'flavs': ['up-ch-dn', 'dn-ch-up'], 'coeffs': [1, 1], 'spin': 0.5}
 * Sigmac0 : {'flavs': ['dn-ch-dn'], 'coeffs': [1], 'spin': 0.5}
 * Xi'c+ : {'flavs': ['up-ch-sr', 'sr-ch-up'], 'coeffs': [1, 1], 'spin': 0.5}
 * Xi'c0 : {'flavs': ['dn-ch-sr', 'sr-ch-dn'], 'coeffs': [1, 1], 'spin': 0.5}
 * Omegac0 : {'flavs': ['sr-ch-sr'], 'coeffs': [1], 'spin': 0.5}
 * Lambdac+ : {'flavs': ['up-dn-ch', 'up-ch-dn', 'dn-ch-up'], 'coeffs': [2, 1, -1], 'spin': 0.5}
 * Xic+ : {'flavs': ['sr-up-ch', 'sr-ch-up', 'up-ch-sr'], 'coeffs': [2, 1, -1], 'spin': 0.5}
 * Xic0 : {'flavs': ['sr-dn-ch', 'sr-ch-dn', 'dn-ch-sr'], 'coeffs': [2, 1, -1], 'spin': 0.5}
 * proton : {'flavs': ['up-dn-up'], 'coeffs': [1], 'spin': 0.5}
 * neutron : {'flavs': ['dn-up-dn'], 'coeffs': [1], 'spin': 0.5}
 * Lambda : {'flavs': ['up-dn-sr', 'up-sr-dn', 'dn-sr-up'], 'coeffs': [2, 1, -1], 'spin': 0.5}
 * Sigma+ : {'flavs': ['up-sr-up'], 'coeffs': [1], 'spin': 0.5}
 * Sigma0 : {'flavs': ['up-sr-dn', 'dn-sr-up'], 'coeffs': [1, 1], 'spin': 0.5}
 * Sigma- : {'flavs': ['dn-sr-dn'], 'coeffs': [1], 'spin': 0.5}
 * Xi0 : {'flavs': ['sr-up-sr'], 'coeffs': [1], 'spin': 0.5}
 * Xi- : {'flavs': ['sr-dn-sr'], 'coeffs': [1], 'spin': 0.5}
 * Omegaccc++ : {'flavs': ['ch-ch-ch'], 'coeffs': [1], 'spin': 1.5}
 * Xi*cc++ : {'flavs': ['ch-up-ch', 'ch-ch-up'], 'coeffs': [2, 1], 'spin': 1.5}
 * Xi*cc+ : {'flavs': ['ch-dn-ch', 'ch-ch-dn'], 'coeffs': [2, 1], 'spin': 1.5}
 * Omega*cc+ : {'flavs': ['ch-sr-ch', 'ch-ch-sr'], 'coeffs': [2, 1], 'spin': 1.5}
 * Sigma*c++ : {'flavs': ['up-up-ch', 'ch-up-up'], 'coeffs': [1, 2], 'spin': 1.5}
 * Sigma*c+ : {'flavs': ['up-dn-ch', 'dn-ch-up', 'ch-up-dn'], 'coeffs': [1, 1, 1], 'spin': 1.5}
 * Sigma*c0 : {'flavs': ['dn-dn-ch', 'ch-dn-dn'], 'coeffs': [1, 2], 'spin': 1.5}
 * Xi*c+ : {'flavs': ['up-sr-ch', 'sr-ch-up', 'ch-up-sr'], 'coeffs': [1, 1, 1], 'spin': 1.5}
 * Xi*c0 : {'flavs': ['dn-sr-ch', 'sr-ch-dn', 'ch-dn-sr'], 'coeffs': [1, 1, 1], 'spin': 1.5}
 * Omega*c0 : {'flavs': ['sr-ch-sr', 'sr-sr-ch'], 'coeffs': [2, 1], 'spin': 1.5}
 * Delta++ : {'flavs': ['up-up-up'], 'coeffs': [1], 'spin': 1.5}
 * Delta+ : {'flavs': ['up-dn-up', 'up-up-dn'], 'coeffs': [2, 1], 'spin': 1.5}
 * Delta0 : {'flavs': ['dn-up-dn', 'dn-dn-up'], 'coeffs': [2, 1], 'spin': 1.5}
 * Delta- : {'flavs': ['dn-dn-dn'], 'coeffs': [1], 'spin': 1.5}
 * Sigma*+ : {'flavs': ['up-up-sr', 'sr-up-up'], 'coeffs': [1, 2], 'spin': 1.5}
 * Sigma*0 : {'flavs': ['up-dn-sr', 'dn-sr-up', 'sr-up-dn'], 'coeffs': [1, 1, 1], 'spin': 1.5}
 * Sigma*- : {'flavs': ['dn-dn-sr', 'sr-dn-dn'], 'coeffs': [1, 2], 'spin': 1.5}
 * Xi*0 : {'flavs': ['sr-up-sr', 'sr-sr-up'], 'coeffs': [2, 1], 'spin': 1.5}
 * Xi*- : {'flavs': ['sr-dn-sr', 'sr-sr-dn'], 'coeffs': [2, 1], 'spin': 1.5}
 * Omega- : {'flavs': ['sr-sr-sr'], 'coeffs': [1], 'spin': 1.5}
 */
const int gamma_1o2_combs = 2;
const static char *gamma_1o2_names = "Pp_Cg5_Cg5, Pm_Cg5_Cg5";
const int baryons_1o2_combs = 20;
const static char *baryon_1o2_names[20] = { "XiccPlPl", "XiccPl", "OmegaccPl", "SigmacPlPl", "SigmacPl", "LambdacPl", "Sigmac0", "XiPrcPl", "XicPl", "XiPrc0", "Xic0", "Omegac0", "proton", "neutron", "Lambda", "Sigma0", "SigmaPl", "SigmaMn", "Xi0", "XiMn", };
const int gamma_3o2_combs = 9;
const static char *gamma_3o2_names = "Pp_Cgx_Cgx, Pm_Cgx_Cgx, gigj_Cgx_Cgx, Pp_Cgy_Cgy, Pm_Cgy_Cgy, gigj_Cgy_Cgy, Pp_Cgz_Cgz, Pm_Cgz_Cgz, gigj_Cgz_Cgz";
const int baryons_3o2_combs = 20;
const static char *baryon_3o2_names[20] = { "OmegacccPlPl", "XiStccPlPl", "XiStccPl", "OmegaStccPl", "SigmaStcPlPl", "SigmaStcPl", "SigmaStc0", "XiStcPl", "XiStc0", "OmegaStc0", "DeltaPlPl", "DeltaPl", "Delta0", "DeltaMn", "SigmaStPl", "SigmaSt0", "SigmaStMn", "XiSt0", "XiStMn", "OmegaMn", };
